# Generated by Django 4.1.5 on 2023-01-21 08:25

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='member',
            name='slug_hash',
            field=models.CharField(default=members.models.generate_slug_hash, max_length=8),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=members.models.today),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
